name: expanse
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  file_picker: ^5.3.3
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  image_picker: ^1.0.2
  mime: ^1.0.4
  pinput: ^3.0.0
  riverpod_annotation: ^2.1.1
  shared_preferences: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.2.5

flutter:
  uses-material-design: true
  assets:
    - 'assets/icons/'
    - 'assets/images/'

flutter_assets:
  assets_path: assets/
  output_path: lib/utils/constants/
  filename: assets.dart

flutter_native_splash:
  color: "#7F3DFF"
  image: "assets/images/splashImage.png"
  color_dark: "#7F3DFF"
  image_dark: "assets/images/splashImage.png"
  android_12:
    color: "#7F3DFF"
    image: "assets/images/splashImage.png"
    color_dark: "#7F3DFF"
    image_dark: "assets/images/splashImage.png"
